//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bootcamp18_crud2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_jurusan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_jurusan()
        {
            this.tbl_mahasiswa = new HashSet<tbl_mahasiswa>();
        }
    
        public int id { get; set; }
        public string nama_jurusan { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_mahasiswa> tbl_mahasiswa { get; set; }
    }
}
