//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bootcamp18_crud2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_mahasiswa
    {
        public int id { get; set; }
        public string nama { get; set; }
        public string alamat { get; set; }
        public Nullable<System.DateTime> tanggal_lahir { get; set; }
        public string no_telp { get; set; }
        public string jenis_kelamin { get; set; }
        public string nama_universitas { get; set; }
        public Nullable<int> id_jurusan { get; set; }
    
        public virtual tbl_jurusan tbl_jurusan { get; set; }
    }
}
